### ISSUE TITLE
Unable to find type [DuckDB.NET.Data.DuckDBConnection] Error with PowerShell 5.1 , version 0.14 of PSDuckDB on Windows 11

### ISSUE THREAD

**Issue by Dolphi2** [dfinke/PSDuckDB#6]
Install-Module -Name PSDuckDB
.
.
Welcome to PSDuckDB! 08/16/2024 08:38:29
Connected to an in-memory database
Unable to find type [DuckDB.NET.Data.DuckDBConnection].

**Comment by dfinke** [comment]
@Dolphi2 thanks for trying the module. I need to update the manifest. Sorry - PS 7.x only
